<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Contact Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'alyssavfortney@gmail.com',
		'to' => 'alyssavfortney@gmail.com'
	),
	'fields' => array(
		'custom_U10606' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U10629' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone\' is required.'
			)
		),
		'custom_U10986' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Do you have a location you prefer?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Do you have a location you prefer?\' is required.'
			)
		),
		'custom_U10998' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'What dates/times are you interested in?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'What dates/times are you interested in?\' is required.'
			)
		),
		'custom_U11010' => array(
			'order' => 8,
			'type' => 'string',
			'label' => 'Any other information I need to know?',
			'required' => false,
			'errors' => array(
			)
		),
		'custom_U11022' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Who will be photographed?',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Who will be photographed?\' is required.'
			)
		),
		'custom_U10853' => array(
			'order' => 4,
			'type' => 'checkboxgroup',
			'label' => 'Type of Session',
			'required' => true,
			'optionItems' => array(
				'Individual',
				'Couple',
				'Family',
				'Other'
			),
			'errors' => array(
				'required' => 'Field \'Type of Session\' is required.',
				'format' => 'Field \'Type of Session\' has an invalid value.'
			)
		)
	)
);

process_form($form);
?>
